### ISSUE TITLE
Readme mistakes in "Setting Up a Virtual Environment"

### ISSUE THREAD

**Issue by Twangist** [mabdullahadeel/Youtube-Video-Downloader#2]
A few:

*  `python -m virtualenv env` should be `python -m venv env`
* The command to activate the virtual environment on *nix should be `source env/bin/activate` not `Source\bin\activate` — case matters. Append ` (Mac, Linux)` not `(mac)`.
* To install dependencies, it's `pip3 install -r requirements.txt` not `python -r requirements.txt`

Thanks!

**Comment by mabdullahadeel** [comment]
> A few:
> 
> * `python -m virtualenv env` should be `python -m venv env`
> * The command to activate the virtual environment on *nix should be `source env/bin/activate` not `Source\bin\activate` — case matters. Append ` (Mac, Linux)` not `(mac)`.
> * To install dependencies, it's `pip3 install -r requirements.txt` not `python -r requirements.txt`
> 
> Thanks!

@Twangist - Thank you very much for pointing this out. I really rushed writing READme that I made these silly mistakes. But thank you very much. I have fixed it.

**Comment by Twangist** [comment]
You're welcome, and thanks for your efforts. (& sorry to post the same issue 2x)
